### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by geeksesi** [geeksesi/Jaipur-telegram-game#1]
this project is based on telegram.
so we need a setup for the telegram to:
- read user messages
- send photo
- send message with inline keyboards
- setup bot keyboards
- chat inline commands
- manage commands
- delete special message
- force them to join on special channel

# tasks
- [x] find a good library
- [ ] on message login or register sender user

**Comment by geeksesi** [comment]
- [ ] refactor commads to run invokable class instead of function
- [ ] text routing ( keyboards, text commands )
